### ISSUE TITLE
ImportError: No module named scan

### ISSUE THREAD

**Issue by aripakman** [sebastien-j/LV_groundhog#3]
when running 
python tutorials/DT_RNN_Tut.py 
I get:

Traceback (most recent call last):
  File "tutorials/DT_RNN_Tut.py", line 5, in <module>
    from groundhog.trainer.SGD_momentum import SGD as SGD_m
  File "/home/aripakman/deepcode/python/LV_groundhog/groundhog/trainer/SGD_momentum.py", line 18, in <module>
    from theano.sandbox.scan import scan
ImportError: No module named scan

**Comment by lvapeab** [comment]
The `scan` function has been moved. Try changing `from theano.sandbox.scan import scan`
by `from theano.scan_module import scan` everywhere it's needed (i.e., probably [here](https://github.com/sebastien-j/LV_groundhog/blob/master/groundhog/trainer/SGD_momentum.py#L18),  [here](https://github.com/sebastien-j/LV_groundhog/blob/master/tutorials/DT_RNN_Tut.py#L31) and [here](https://github.com/sebastien-j/LV_groundhog/blob/master/groundhog/layers/rec_layers.py#L18)).

**Comment by aripakman** [comment]
thanks!
