### ISSUE TITLE
normal behavior ?

### ISSUE THREAD

**Issue by vince62s** [sebastien-j/LV_groundhog#4]
Hello,
Just to make sure, I don't have any misunderstanding ....
in encdec.py I have to add "on_unused_input = 'ignore' " on the lines:
def create_next_states_computer(self): ..... in the theano.function
and
def create_probs_computer(self ......in the theano.function.
otherwise it throws an error when running sample.py
maybe I am doing something wrong ?
thanks,
V.

**Comment by sebastien-j** [comment]
This is normal.See "Known issues" in the readme at [...]/experiments/nmt.

**Comment by vince62s** [comment]
Yes I figured it out sorry.
Two other questions :
1) the section reloading model with the "fixes" before reloading, is this only for the LV section ? ie, model reloading will work without these fixes in the regular training ?
2) I read that aligning with fast_align is optional, but I understand this is also the process that will generate the topn files. So if I want to use fast_sample.py do I really need to fast_align ?

thanks,
