### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by HongyuGong** [sebastien-j/LV_groundhog#6]
Hi, I run train.py on 800M selected news corpus, and I have done all preprocessing steps before training. It only takes me several hours to run train.py on a linux server, and the translation performance is bad. Is such short training time normal? To get a good model, do I need to reshuffle the corpus and resume training again? Thanks!

**Comment by sebastien-j** [comment]
You may not need to reshuffle the data, but you should most likely resume training. What was your stopping criterion?

**Comment by HongyuGong** [comment]
Hi I have found the problem -- the limit of running time is set to be small. Thank you!
